pipelines:
    branches:
      main:
        - step:
            name: Build and Deploy
            script:
              - git remote add origin https://github.com/single-developer/ecommerce-backend.git
              - git branch -M main
              - git push -u origin main